### PR TITLE
Spanish Translations

### PR DESCRIPTION
**Pull request by jamezrin**

### CODE REVIEW

**Review by BadPixxel — COMMENTED** [review]
Hi, this is useless, only definition of languages used for Travis CI. So no use to push this.
BR

**Review by BadPixxel — APPROVED** [review]

**Comment by jamezrin** [comment]
Hi, thank you. I haven't tried splashsync yet so I didn't know where to translate stuff.
Is everything translatable on https://github.com/SplashSync/Dolibarr/tree/master/splash/src/Translations?
Is there any other place for strings?

**Review by BadPixxel — COMMENTED** [review]
Can you please remove this change? It makes CI fail.

**Comment by jamezrin** [comment]
Done deal @BadPixxel

**Pull request merged**
