### PR TITLE
fix : include with dolibarr custom or other install

### PR DESCRIPTION
**Pull request by ghost**
use dol_include_once and method declaration to avoid warning in php 7

### CODE REVIEW

**Comment by ghost** [comment]
Better view of diff without space and balnk comapre https://github.com/SplashSync/Dolibarr/pull/3/files?w=1

**Comment by BadPixxel** [comment]
Hi,

Did you tests the same change here : 
https://github.com/SplashSync/Dolibarr/blob/23da3bd7f5f2182499a88f7dbd1e90ad57da768b/splash/src/Local.php#L176

This include is done when connecting from remote.

**Comment by ghost** [comment]
To be honest, I just fix the fatal when I just install the module and go to setting page in Dolibarr. 
I didn't try to do a real end to end setup. 
We can discuss about this during Dolibarr DevCamp next week end ;-)

**Comment by BadPixxel** [comment]
Ok, thanks, I'll do it and valide this PR.
The fatal is only on V7 right?

**Comment by ghost** [comment]
Waring in V7 only, but other fatal in 5.6 also. I think it's because I use a special installation directory with linux symbolic links into custom dolibarr directory rather than deploy module into htdocs/custom directly. Do not valid the PR now, we will check together

**Comment by BadPixxel** [comment]
Ok!!

**Pull request merged**
